### ISSUE TITLE
should not add semicolon if line already ends with a semicolon

### ISSUE THREAD

**Issue by pascalpp** [pimartin/trailing-semicolon#1]
If the line already ends with a semicolon or comma , this package should not add an additional semicolon/comma. This would be particularly useful when editing multiple lines.

**Comment by pimartin** [comment]
I'm aware of this problem and I will look into it now that I know it bothers someone else ;-)

**Comment by pimartin** [comment]
This is fixed with the 0.1.1 version.

**Comment by pascalpp** [comment]
um that was fast! thanks :beers:

**Comment by pimartin** [comment]
You're welcome.
I forgot : I might update this package to handle selections spanning over multiple lines. If I do, I will probably make it toggle the semicolon if only one line is selected and ignore the lines that already have one if multiple lines are selected (by default). But I will add settings to change that behaviour if needed.
So if at some point it stops behaving the way you like, remember to check the (future) settings.

**Comment by pascalpp** [comment]
gotcha. fwiw, it seems reasonable to me to expect people to convert a multiline selection into multiple cursors before triggering add semicolon.
