### ISSUE TITLE
what about skipping to a new line?

### ISSUE THREAD

**Issue by flipside** [pimartin/trailing-semicolon#2]
So far I like the functionality, but it would also be nice if there was a combo for adding a semicolon and starting a new line. Maybe `ctrl-shift-;` and `ctrl-shift-,`?

**Comment by pimartin** [comment]
There is `ctrl-enter` (by default in Atom) that allows you to start a new line wherever you are in the current line. Would that suit your need despite needing another key press ?

If it doesn't, I think your request would be easy to implement (although I would be reluctant to add yet another key mapping by default).

**Comment by flipside** [comment]
Yeah, that works too. There's also just going to the end of the line. 

It would definitely be worth adding the functionality without default keybindings.

Also, `ctrl-shift-;` is a horrible idea, `ctrl-alt-;` is way easier to use.

**Comment by pimartin** [comment]
I updated the package, there are two new commands named `trailing-semicolon:semicolon-newline` and `trailing-semicolon:comma-newline` to start a new line after adding the semicolon/comma. It behaves exactly like `ctrl-enter`.

There is also a new setting that allows you to enable this behavior for the default commands.
